#!/usr/bin/env ruby

version   = "#{ARGV.last.match(/\d+/) || 3}".to_i
command   = ({"console" => {2 => "script/console", 3 => "rails c"}}[ARGV.first] || {2 => "script/server", 3 => "rails s"})[version]
dummy_app = File.expand_path("../rails-#{version}/dummy", __FILE__)

system "rake restore:rails-#{version} && cd #{dummy_app} && #{command}"