# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rich_cms}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Engel"]
  s.date = %q{2010-08-15}
  s.description = %q{Rich-CMS is a module of E9s (http://github.com/archan937/e9s) which provides a frontend for your CMS content. You can use this gem to manage CMS content or translations (in an internationalized application). The installation and setup process is very easily done. You will have to register content at the Rich-CMS engine and also you will have to specify the authentication mechanism. Both are one-liners.}
  s.email = %q{paul.engel@holder.nl}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "app/controllers/rich/cms_controller.rb",
     "app/views/rich/cms/_bar.html.erb",
     "app/views/rich/cms/_config.html.erb",
     "app/views/rich/cms/bar/_menu.html.erb",
     "app/views/rich/cms/bar/_panel.html.erb",
     "app/views/rich/cms/bar/panel/_edit.html.erb",
     "app/views/rich/cms/bar/panel/_login.html.erb",
     "app/views/rich_cms.html.erb",
     "assets/jzip/jquery/core.js",
     "assets/jzip/jquery/extensions/ajaxify.js",
     "assets/jzip/jquery/extensions/modules.js",
     "assets/jzip/jquery/extensions/object.js",
     "assets/jzip/rich.js",
     "assets/jzip/rich/cms.js",
     "assets/jzip/rich/cms/editor.js",
     "assets/jzip/rich/cms/login.js",
     "assets/jzip/rich_cms.jz",
     "assets/sass/_bar.sass",
     "assets/sass/_editables.sass",
     "assets/sass/_mixins.sass",
     "assets/sass/rich_cms.sass",
     "config/routes.rb",
     "init.rb",
     "install.rb",
     "lib/rich/cms/actionpack.rb",
     "lib/rich/cms/actionpack/action_controller/base.rb",
     "lib/rich/cms/actionpack/action_view/base.rb",
     "lib/rich/cms/content/group.rb",
     "lib/rich/cms/content/item.rb",
     "lib/rich/cms/engine.rb",
     "lib/rich_cms.rb",
     "rails/init.rb",
     "rich_cms.gemspec",
     "tasks/rich_cms_tasks.rake",
     "test/engine_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/archan937/rich_cms}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Enrichments (e9s) module for a pluggable CMS frontend}
  s.test_files = [
    "test/engine_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jzip>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 3"])
      s.add_runtime_dependency(%q<formtastic>, [">= 0"])
    else
      s.add_dependency(%q<jzip>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 3"])
      s.add_dependency(%q<formtastic>, [">= 0"])
    end
  else
    s.add_dependency(%q<jzip>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 3"])
    s.add_dependency(%q<formtastic>, [">= 0"])
  end
end

