source "http://rubygems.org"

gem "rails", "2.3.10"
gem "sqlite3-ruby", :require => "sqlite3"

gem "rich_cms", :path => File.join(File.dirname(__FILE__), "..", "..", "..")

gem "shoulda"
gem "mocha"
gem "capybara"
gem "launchy"