source "http://rubygems.org"

gem "rails", "<%= rails_gem_version %>"
gem "mysql"
<%= auth_gem %>
gem "rich_cms", :path => File.expand_path("../../../..", __FILE__)

group :test do
  gem "shoulda"
  gem "mocha"
  gem "hpricot"
end