source "http://rubygems.org"

gem "rails", "3.0.5"
gem "sqlite3-ruby", :require => "sqlite3"

gem "authlogic"
gem "devise", "~> 1.1.5"
gem "rich_cms", :path => File.expand_path("../../../..", __FILE__)

group :test do
  gem "mysql"
  gem "shoulda"
  gem "mocha"
  gem "hpricot"
end