source "http://rubygems.org"

gem "rails", "2.3.11"
gem "sqlite3-ruby", :require => "sqlite3"

gem "authlogic"
gem "devise", "~> 1.0.9"
gem "rich_cms", :path => File.expand_path("../../../..", __FILE__)

group :test do
  gem "shoulda"
  gem "mocha"
  gem "hpricot"
end