source "http://rubygems.org"

gem "rails", "3.0.3"
gem "sqlite3-ruby", :require => "sqlite3"

gem "rich_cms", :path => File.join(File.dirname(__FILE__), "..", "..", "..")

gem "shoulda"
gem "mocha"
gem "capybara"
gem "launchy"
gem "jeweler"