source "http://rubygems.org"

gem "rails", "3.0.3"
gem "jeweler"
gem "sqlite3-ruby", :require => "sqlite3"

gem "authlogic"
gem "devise", "~> 1.1.5"
gem "rich_cms", :path => File.join(File.dirname(__FILE__), "..", "..", "..")

gem "mysql2"
gem "shoulda"
gem "mocha"
gem "capybara"
gem "launchy"